name: Install the extension
on: [pull_request]

jobs:
  install:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install and run the extension from source
     env:
      GH_TOKEN: ${{ github.token }}
     run: |
      go build -o gh-projects projects.go
      gh extension install .
   - name: View a project
     env:
      GH_TOKEN: ${{ github.token }}
     run: |
       gh projects view 4247 --org github
