name: Install the extension
on: [pull_request]

jobs:
  install:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install and run the extension from source
     env:
      GH_TOKEN: ${{ github.token }}
     run: |
      go build -o gh-projects projects.go
      gh extension install .
   - name: List projects
     env:
      GH_TOKEN: ${{ github.token }}
     run: |
      gh projects list --org microsoft
