name: Install the extension
on: [pull_request]

jobs:
  install:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: Install the extension
     env:
      GH_TOKEN: ${{ github.token }}
     run: go build projects.go && gh extension install .

   - name: List Projects
     env:
      GH_TOKEN: ${{ github.token }}
     run: gh projects list --org microsoft